input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # Grok parse for different logs. We will introduce intentional grok issues for the Easy stage.
  if [log_type] == "billing_service" {
    # INTENTIONAL BUG: Real format might be "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}", but we mismatch it.
    grok {
      # The worker logs this format: "Some sentence. [from 192.168.1.1]"
      match => { "message" => "%{GREEDYDATA:msg} \[from %{IP:client}\]" }
      tag_on_failure => ["_grokparsefailure_billing"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "changeme"
    index => "logstash-%{[log_type]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
